### ISSUE TITLE
Repository Name

### ISSUE THREAD

**Issue by ccoffrin** [huckl3b3rry87/NLOptControl.jl#1]
The Julia convention seems to be that package repository names include the `.jl`, so you might want to rename this one `NLOptControl.jl`

Also this line from the README.md does not appear to be accurate at the moment,
```
Pkg.clone("https://github.com/huckl3b3rry87/NLOptControl.jl")
```
This proposed change would fix both points. 🚀

**Comment by huckl3b3rry87** [comment]
Good, catch! Thanks for the feedback!
