### ISSUE TITLE
Possible Setup

### ISSUE THREAD

**Issue by ChrisRackauckas** [huckl3b3rry87/NLOptControl.jl#3]
Let me expand a little bit about what I said in the chat. You can create a nonlinear constraint from any user-definable autodifferentiable function. See http://www.juliaopt.org/JuMP.jl/0.15/nlp.html#user-defined-functions . 

So, what could be done is a function can be generated from the ODE. https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/blob/master/src/DiffEqParamEstim.jl#L39 shows how to make a cost function on the parameters which can be autodifferentated. A possible interface could be:

```julia
@ODEconstraint(mdl, xdot = (prob,alg,u0,p), sol[i] = ...)
```

So the first part are the problem (the ODE to solve), the algorithm to solve it with, maybe some parameters etc., the initial condition, and `p` is the parameters. Then next is the constraint you place on the ODE solution. For example:

```julia
@ODEconstraint(mdl, xdot = (prob,alg,x[1:2],x[3:6]), sum(sol[1:2]) < 2)
```

would mean that the first two optimization variables become the initial condition, and the next four are the parameter values. Then you can, from the macro, write a function which puts those in and gives the solution at the end using the problem that's defined:

```julia
    calc_end_from= function (input) # Has prob / alg enclosed in it already
     u0 = input[1:2]; p = input[3:6]
      f = (t,u,du) -> prob.f(t,u,p,du)
      uEltype = eltype(p)
      
     # If u0 is not given, use the initial conditions from the `prob` itself
     #u0 = [uEltype(prob.u0[i]) for i in 1:length(prob.u0)]
      tspan = (uEltype(prob.tspan[1]),uEltype(prob.tspan[2]))
      temp_prob = ODEProblem(f,u0,tspan)
      if alg == nothing
        sol = solve(temp_prob;saveat=t,save_timeseries=false,dense=false,kwargs...)
      else
        sol = solve(temp_prob,alg;saveat=t,save_timeseries=false,dense=false,kwargs...)
      end
      sol[end]
      end
```

This function should be autodifferentiable, and so then you should be able to just register it and make the constraint:

```julia
JuMP.register(:calc_end_from, 2, calc_end_from, autodiff=true)
@NLexpression(m, myexpr[i=1:6], calc_end_from(x[i]))
@NLconstraint(m, myconstr[i=1:6], sum(myexpr[i]) < 2)
```

The `@ODEconstraint(mdl, xdot = (prob,alg,u0,p), sol[i] = ...)` could then just expand to this.

Note: The way this is written, it requires that the problem was defined via a `ParameterizedFunction` or some other function for which the input style `f(t,u,p,du)` where `p` are the parameters exists (which is something `ParameterizedFunctions computes automatically, but users could provide as an extra dispatch to any arbitrary function)

**Comment by ChrisRackauckas** [comment]
Note that this format can be optimized a little to get rid of the temporary constructions on the anonymous functions. Instead of closures, one could write a wrapper where you can mutate the parameters and holds the closure as its call. For an example, see:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/derivative_wrappers.jl

But to make this strictly typed, you need to have a separate dispatch for whether `input<:Dual` vs `input<:Number`, since if you strictly type the closure wrapper, then it won't work for both standard numbers and duals.

**Comment by huckl3b3rry87** [comment]
This is extremely helpful @ChrisRackauckas, thank you very much once again for the insight! I will begin to implement this!

**Comment by huckl3b3rry87** [comment]
@ChrisRackauckas  I just added the first example where I solve an optimal control problem here:
https://github.com/huckl3b3rry87/NLOptControl.jl/blob/master/examples/OCP/Example%201.ipynb

which is the same problem shown here:
http://www.gpops2.com/Examples/Bryson-Denham.html

It definitely needs work ( developing the actual @ODE macro and registering functions). I just wanted to demonstrate that it is now working at a basic level!! 

What do you think ? Any other suggestions now that you see how I am doing it?

Thanks!

**Comment by huckl3b3rry87** [comment]
I am closing this, because I just finished the initial setup. Thanks again for your suggestions @ChrisRackauckas
